[package]
name = "mkv"
version = "0.1.0"
authors = ["quadrifoglio <quadrifoglio.clement@protonmail.com>"]

[dependencies]
error-chain = "0.11.0"

[dependencies.ebml]
git = "https://github.com/quadrifoglio/ebml"
